### ISSUE TITLE
Nav Links

### ISSUE THREAD

**Issue by TyannaB** [Sebby-T/animal-rescue-website#3]
Your links throughout your nav bar seem to not all be connected your first three don't do anything? not sure if it's cuz you may not be done or not. But thought I'd let you know! Beautiful site though !!

**Comment by Sebby-T** [comment]
No they were placed there because they would actually be there on a real website, they didn't have to lead anywhere though. It's an aesthetic touch that adds to the realism of the webpage. But if I'm feeling it later when I have time, I may actually code those webpages for a portfolio presentation.

Thanks though!
